apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankofanthos-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx

    # Force redirect HTTP -> HTTPS (Control CD2-02)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # rate limit (Control CD2-04)
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
    - hosts:
        - bankofanthos.local
      secretName: boa-tls
  rules:
    - host: bankofanthos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80